name: PHP Composer ARM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        extensions: ['ast, grpc', 'ast, grpc, protobuf']

    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
    - name: Test 
      run: |
            docker run --rm -v ${{ github.workspace }}:/io:rw --workdir=/io \
            arm64v8/ubuntu \
            bash -exc 'apt-get update && \
            apt install software-properties-common -y && \
            add-apt-repository ppa:ondrej/php && \
            apt-get update && \
            apt -y install php7.4 && \
            apt-get install -y php7.4-cli php7.4-json php7.4-common php7.4-mysql php7.4-zip php7.4-gd php7.4-mbstring php7.4-curl php7.4-xml php7.4-bcmath && \
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
            php composer-setup.php && \
            php -r "unlink('composer-setup.php');" && \
            mv composer.phar ~/.local/bin/composer && \
            composer --version && \
            composer validate && \
            apt install openssl php-common php-curl php-json php-mbstring php-mysql php-xml php-zip && \
            apt-get install -y php-ast php-grpc php-protobuf && \
            apt-get install -y php-cs-fixer && \
            composer install --prefer-dist --no-progress --no-suggest && \
            composer update && \
            vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php --dry-run --stop-on-violation --using-cache=no -vvv && \
            vendor/bin/deptrac --formatter=github-actions && \
            PHAN_DISABLE_XDEBUG_WARN= 1 && \
            vendor/bin/phan && \
            vendor/bin/psalm --output-format=github && \
            vendor/bin/phpstan analyse --error-format=github && \
            vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover --testsuite unit && \
            vendor/bin/phpunit --testsuite integration'
            
            
            
           
            
            
      
      
